# Generated by Django 4.0.4 on 2022-07-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjopinie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Opis lektoratu'),
        ),
        migrations.AddField(
            model_name='subject',
            name='url',
            field=models.URLField(blank=True, help_text='Zewnętrzny link do opisu danych zajęć', verbose_name='link'),
        ),
    ]
